# version: '3'
# services:
#   rabbitmq:
#     image: rabbitmq:3.13-management
#     ports:
#       - "5672:5672"  # RabbitMQ port
#       - "15672:15672"  # RabbitMQ management UI port

#   backend:
#     build: .
#     ports:
#       - "8080:8080"  # Your Golang application port
#     depends_on:
#       - rabbitmq


# version: '3'

# services:

#   backend:
#     build: .
#     ports:
#       - "8080:8080"  # Your Golang application port
    

#   rabbitmq:
#     image: rabbitmq:3.13-management
#     ports:
#       - "5672:5672"  # RabbitMQ port
#       - "15672:15672"  # RabbitMQ management UI port

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"  # Expose Nginx on port 80
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf  # Mount Nginx configuration file
#     depends_on:
#       - backend
#       - rabbitmq


version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672"  # RabbitMQ management UI port
      
  backend:
    build: ./backend
    ports:
      - "8080:8080"  # Your Golang application port
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  node-server:
    build: ./node_server
    ports:
      - "5005:5005"  # Your Node.js application port
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount Nginx configuration file
    depends_on:
      - backend
      - rabbitmq
      - node-server

